### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by andysc** [seanmtracey/GlowOrb-Emulator#11]
Even though my other client is connected to MQTT.cheerlights.com:1883 from here, the GlowOrb won't connect.
Settings are :

<img width="309" alt="Screenshot 2019-07-08 at 17 44 50" src="https://user-images.githubusercontent.com/2693674/60827438-1b883600-a1a8-11e9-9bfd-bcb6de31d178.png">

<img width="704" alt="Screenshot 2019-07-08 at 17 43 59" src="https://user-images.githubusercontent.com/2693674/60827403-06130c00-a1a8-11e9-9e5b-b0dad32372bd.png">

**Comment by seanmtracey** [comment]
Patched in #12. Will release pre-built app with update shortly.
