### ISSUE TITLE
after examining the settings, escape should exit the dialogue without change

### ISSUE THREAD

**Issue by andysc** [seanmtracey/GlowOrb-Emulator#3]
If it's connected to the broker I wanted, or just to remind myself which topic I set, hitting esc to clear the dialogue would be good, rather than having to click save settings, which (presumably?) triggers a reconnect. 
Not that that's bad.. just an action that isn't needed

**Comment by seanmtracey** [comment]
Yup, totally reasonable ask.

Will add the "esc" shortcut, but will also replace the save settings button with a "Save/Cancel" combo so there's a visible cue for those who don't want to make a change.

**Comment by andysc** [comment]
good answer :)

**Comment by seanmtracey** [comment]
Feature added in https://github.com/seanmtracey/GlowOrb-Emulator/commit/ca8bfeb7a4b1c6dac16c8a7033c2f3e0c7db98ef.
