### ISSUE TITLE
settings "cog" is a long way from the gloworb graphic when it's in "connecting" state

### ISSUE THREAD

**Issue by andysc** [seanmtracey/GlowOrb-Emulator#4]
If you get the settings wrong and it can't connect, you don't get the colour label box that's underneath the gloworb graphic.
In this state, the settings cog button is 3cm away, and is very hard to spot for first-time users.

Suggest moving it a lot closer to the gloworb graphic

**Comment by seanmtracey** [comment]
My bad, it is a little far looking at it now.

Think I'll replace the cog with a prominent "Settings" link in the information dialog showing the latest update info.

**Comment by andysc** [comment]
where is the information dialogue? The only option I can see is Quit

**Comment by seanmtracey** [comment]
Adding functions to the taskbar menu is one of the few things that's hard work in Electron. It's on my list to add an "About" dialog as well as some smaller functions to there

**Comment by andysc** [comment]
where did you mean, then, for the information dialogue?

**Comment by seanmtracey** [comment]
One sec, just to make sure we're not crossing wires here:

When you say information dialog, do you mean a dialog with information about the app, or a dialog with information about the current connect settings?

**Comment by andysc** [comment]
I mean whatever you meant in 
`Think I'll replace the cog with a prominent "Settings" link in the *information dialog* showing the latest update info.`
I have no further context

**Comment by seanmtracey** [comment]
Ah, gotcha! So the window just beneath the GlowOrb itself is what I've been calling the *information dialog* (dialog isn't a great word, thinking about it) where the latest RGB color has been received by the emulator. Just beneath that is the new "connection settings" button, which you can see if the [0.2.0-beta](https://github.com/seanmtracey/GlowOrb-Emulator/releases/tag/0.2.0-beta) release

**Comment by andysc** [comment]
ah, that's what you're on about ;)
Colour has a u in it, btw (in the information "dialog") ;)

**Comment by seanmtracey** [comment]
I gave up on the 'u' in 'colour' years ago. Too much pain was suffered in CSS to try and keep the two straight in my head, so it's just 'color' these days.

**Comment by seanmtracey** [comment]
Cog replaced with `Connection Settings` button in https://github.com/seanmtracey/GlowOrb-Emulator/commit/95030e861bba024bd337902a1685d7b9a58e9d0b.
