### ISSUE TITLE
font seems a bit clipped

### ISSUE THREAD

**Issue by andysc** [seanmtracey/GlowOrb-Emulator#6]
0.2.0-beta
I like everything else you've done, but the "connected" string looks like it's clipped across the top (the top of the t and ns). 
Either that or it's a weird font and I don't like it ;)
Sorry to be picky
<img width="280" alt="Screenshot 2019-06-20 at 18 25 01" src="https://user-images.githubusercontent.com/2693674/59868610-3a559280-9389-11e9-811a-0f6b48a44c5b.png">

**Comment by seanmtracey** [comment]
It's the font being the font 😅

I wanted a font that was tall and bold for the connection states, the 't' is a little bit odd, so I'll look into alternatives.

**Comment by seanmtracey** [comment]
Changed font in https://github.com/seanmtracey/GlowOrb-Emulator/commit/597598d163e7612fc4b0009ab597357568fc725b.
