### ISSUE TITLE
can't change settings in "connectinG" state

### ISSUE THREAD

**Issue by andysc** [seanmtracey/GlowOrb-Emulator#7]
0.2.0-beta
if it can't connect to a valid broker, and is in "connectinG..." state, clicking on Connection Settings does nothing, so you can't ever get out of that situation by putting in valid settings.

**Comment by seanmtracey** [comment]
Just noticing this myself now, will look at debugging towards the end of the week.

**Comment by seanmtracey** [comment]
Addressed in https://github.com/seanmtracey/GlowOrb-Emulator/commit/d0a74ef21a3c9f95a1bd546251a7e869507cc4f9,
